### ISSUE TITLE
Preventing multiple hotfixes

### ISSUE THREAD

**Issue by cwarren-mw** [petervanderdoes/gitflow-avh#143]
As I understand it, git flow will refuse to create a new hotfix if one already exists in the local repository. Would it be possible (or desirable) to prevent hotfix creation if there's an existing hotfix branch on the remote repository? Right now, multiple users can create and publish hotfixes at the same time, which is a state I would prefer to avoid if possible.

Thank you.

**Comment by gabeio** [comment]
The point behind branching is for anyone to be able to make a branch and create hotfixes for you. As such there is no possible way to tell if another user has started a hotfix except by pulling from everyone's local repo... and only if there already is a hotfix branch present to fail but this is basically impossible.

**Comment by baby-gnu** [comment]
-1

And I think this is not desirable.

All hotfix are not equals.

You have several hotfix branches and you are testing them to see if they play well together.

Suddenly, you find a security bug, you want to postpone all the other hotfixes to pass this one.

Regards.

**Comment by jrial** [comment]
Personally, I consider the fact you can't create multiple hotfixes a bug. My current hotfix can be interrupted for a more urgent security fix, and the process should support this instead of telling me "you're not allowed to do that". It wants to throw me a warning, asking for my express consent in the process even, fine. But allow it.

It's already possible for two developers to have separate local hotfix branches, and even for both of them to have pushed it to a common upstream repo, leading to exactly the same issues this restriction is trying to avoid. There is no way you can prevent this, so it needs to be dealt with anyway. At that point, the local restriction becomes pointless.

**Comment by petervanderdoes** [comment]
Juan (@jrial),

you can actually set a config by hand that allows for multiple hotfixes.
`git config set gitflow.multi-hotfix true`
as per commit

**Comment by jkankiewicz** [comment]
> Personally, I consider the fact you can't create multiple hotfixes a bug.

Another reason for allowing multiple hotfix branches to exist in the same clone is when a new hotfix branch is based upon an older one.  This situation can arise when the new hotfix depends upon the changes in the older hotfix but the older hotfix's branch hasn't been merged into the master/support branch yet because it's still pending review, validation, etc.
