### ISSUE TITLE
Cygwin installation instructions from wiki do not work

### ISSUE THREAD

**Issue by mrt181** [petervanderdoes/gitflow-avh#191]
When I follow the instructions I get this nothing more:

```
$ wget -q -O - --no-check-certificate https://raw.github.com/petervanderdoes/gitflow/develop/contrib/gitflow-installer.sh install stable | bash
### git-flow no-make installer ###
Usage: [environment] gitflow-installer.sh [install|uninstall] [stable|develop]
Environment:
   PREFIX=/usr/local
   REPO_HOME=https://github.com/petervanderdoes/gitflow.git
   REPO_NAME=gitflow
```

When i first download the script and then start the script it works

```
$ wget - --no-check-certificate https://raw.github.com/petervanderdoes/gitflow/develop/contrib/gitflow-installer.sh
$ bash gitflow-installer.sh install stable
```

**Comment by gene-pavlovsky** [comment]
I've had same problem. The second way to do it succeeded to install, but the installed files had Windows line endings (CRLF), and didn't work. I had to
```
wget --no-check-certificate https://raw.github.com/petervanderdoes/gitflow/develop/contrib/gitflow-installer.sh
bash gitflow-installer.sh install stable
cd gitflow
git config core.autocrlf input
git rm --cached -r .
git reset --hard
cd ..
bash gitflow-installer.sh install stable
```
(Or `make install` instead of the last two lines).
My `core.autocrlf` is set to `true` in the global git config (per github's recommendations, maybe it's not such a great idea). In my own projects involving shell scripts or other files where line endings are important, I create a `.gitattributes` file and specify which files should be LF, e.g.
```
* text=auto
*.awk  text eol=lf
*.sed  text eol=lf
*.sh   text eol=lf
```
Maybe this repo could have a .gitattributes file as well?

**Comment by RDyego** [comment]
@gene-pavlovsky Thx.

**Comment by weynelucas** [comment]
Thanks!
