### ISSUE TITLE
Starting hotfix with dirty develop

### ISSUE THREAD

**Issue by spiroski** [petervanderdoes/gitflow-avh#195]
Many times, I forget to start a hotfix before I start working on the problem.

Then when trying to start a hotfix I get:
`Fatal: Working tree contains unstaged changes. Aborting.`

The easiest solution for me is to:
- git stash
- git flow hotfix start
- git stash apply

Now we as developers want to save as much time as possible, so for this scenario maybe we could add option to `git flow hotfix start --stash` to stash the changes, create the hotfix and then apply the stashed changes.

Do you think something like this should be implemented? If yes, I will try to do it and submit a PR.

**Comment by Grinderofl** [comment]
This is yet again something that needs to be brought up! There are numerous reasons I could start listing here, but for one, if I can perform the exact steps git flow does, **manually**, without having to do a stash before and stash pop after, then git flow should be able to, too. This is an incredibly frustrating bug (I call it a bug, because really - it may be a 'feature' of git flow, but git itself certainly does not behave this way)!

While we're at it, could we also take care of the **even more** annoying "no multiple concurrent hotfixes" crap? Again, in the world of devops, it's not uncommon at all to have multiple hotfix branches you're working on simultaneously.


Perhaps a 'advanced mode' that can be toggled during git init? if configured, all the 'safety checks' would be lifted?

**Comment by Grinderofl** [comment]
And yet again, will keep bumping this until it gets resolved! I just spent an hour trying to figure out why I kept getting errors on my database on a project I haven't worked with in a while - before discovering that "oh, I had to use a different web.config, which I do not ever commit in during normal usage, but have to stash every time I commit, and I forgot to unstash it the last time I committed". Good devops are able to rely on the tools they use to make their lives easier, more structured and reliable, while being able to automate everything they do. This single "feature" is causing slowdowns and hiccups in an otherwise well-functioning workflow. I shouldn't need to remember to git stash before and git stash pop after every git flow operation! No, I will not bake them into an alias. Stashing and unstashing causes working changes to be re-staged in github which could cause an accidental commit. 

**Please remove the requirement for clean working trees prior to git flow operations.**

**Comment by jrial** [comment]
@spiroski 

For hotfix start or feature start, I agree that this would make sense, assuming you're already on the base branch. Otherwise your stash pop could lead to merge conflicts. You'll also have these if you do it manually, but GF should try to avoid causing problems that need manual intervention if possible, IMHO.


@Grinderofl 

Re. "multiple hotfixes": a google search for `gitflow-avh multiple hotfix branches` turns up issue #167 as the very first hit, describing this exact problem. It was implemented in commit 7cab2a25c501ad43878fa08b6fdfd309e550a8a5 which is dated Dec. 24, 2014. It was further refined in commit 5b87733f7e756103d52b8434d61b0bc895505a3b on Jul. 26, 2016.

Furthermore, it's not the subject of this issue. Even if it had been a legitimate complaint, it should've been filed in a separate issue.

Re. "clean working trees": that web.config does not belong with your code. Business logic and per environment configuration should be kept separate, and combined by your deploy script during rollout.

In general, if your workspace is still dirty by the time you need to switch branches, odds are you're doing something wrong. Even if you're not, the few seconds you lose by running git stash save, followed by <up><up><enter> are negligible compared to the time you spent (or will spend) making your changes and sorting them into clear and separate commits. Hardly worth getting worked up about.

**Comment by Grinderofl** [comment]
@jrial I wrote an epistle of a comment, and deleted it all to say this one thing all over again:

**Tools like gitflow should fit into the users' workflows, not the other way around. Forcing a clean working tree _invariably for all users_ is an artificial limitation. The only solution is to provide a configuration flag for git flow that allows users to say "I know wtf I'm doing. Stop limiting me"!**



PS: I'm sure I'm not the only person who has heard of Azure AppSettings...

**Comment by jrial** [comment]
@spiroski actually, come to think of it, is it even necessary to add a `--stash` flag in the first place? It might be handy for other reasons, but the way I see it if the branch change can be performed without stashing at all, it's a redundant step. In your use case, we start from the base branch (unless I read you wrong), so no branch change is even required.

If, on the other hand, you started your development on a branch that's not the base branch of the new hf/feat/... and your changes would cause a merge conflict when switching to the base branch, you probably *don't* want to stash and pop automatically and end up in a conflicted state.

The short: the "clean workspace" requirement can be removed, IMHO, assuming the first action is to switch to the base branch, and no other action is performed unless this succeeds.


@Grinderofl Using all bold (the new all caps?) does not lend weight to your arguments. Nor do tantrums and grumbling.

Now, if you think you can stay civilised, let me offer you my counter-argument: no, not every tool should fit every user's workflow all the time. As a user, it is your responsibility to select the tools that best fit yours. Those are not necessarily the tools that best fit the rest of us.

Git-flow already enforces a workflow on its end user, and the reason for that is that it tries to streamline best practices and a maintainable branching strategy. The goal of this tool is to assist people in an organised and maintainable approach to software development and delivery. And if it errs on the side of caution when doing so, leading to a short interruption while you get your stuff in order, I think it can be forgiven. However, it's a lot harder to forgive a tool for messing up your code and wasting your afternoon recovering from that.

**Comment by petervanderdoes** [comment]
@Grinderofl  
> Tools like gitflow should fit into the users' workflows

This is just impossible. One could argue that there is a workflow for every user. 

- "My repository is located on GitHub and the tool should be able to use the PR functionality"
- "My repository is located on Gitlab and the tool should be able to use the Merge Request functionality"
- "My repository is located on Bitbucket and the tool should be able to use the PR functionality"
- "I have repositories located on multiple sites and the tool should accommodate this"

> Good devops are able to rely on the tools they use to make their lives easier, more structured and reliable, while being able to automate everything they do

They also know the limitations of the tools they use and if they think the tools is missing something and the tool is open source they will see if they can contribute to a solution.

> I shouldn't need to remember to git stash before and git stash pop after every git flow operation! No, I will not bake them into an alias. Stashing and unstashing causes working changes to be re-staged in github which could cause an accidental commit.

Wait. So you don't want to create an alias which will stash/unstash before/after a git-flow operation because it could cause an accidental commit but you do want the tool to an automatic stash and unstash? I'm confused.

**Comment by jrial** [comment]
@petervanderdoes 
> Wait. So you don't want to create an alias which will stash/unstash before/after a git-flow operation because it could cause an accidental commit but you do want the tool to an automatic stash and unstash? I'm confused.

No, the way I understand it is he wants git-flow to simply start a hotfix/feature/... without stashing at all.

I do agree with him that there probably is no need to require a clean working folder when starting a new branch, given some conditions:

- One is already on the base branch for the new branch (master for a new hotfix, develop for a new feature, release).
- Or checking out the base branch is possible (git will refuse if the local changes conflict with a diff between the current branch and the one you're trying to check out).

I think it simply boils down to skipping the clean branch check when starting a new branch, and have the "git checkout ${base_branch}" be the canary instead.

This of course, only applies to starting, not finishing.

**Comment by Grinderofl** [comment]
@petervanderdoes 

When I say "tools should fit into users' workflows", it's probably more accurate to say "popular tools should not lock you into a single workflow". While I agree that "GitFlow the Workflow" is fine the way it is, I don't think that "git flow the Tool" however should force it onto you, as if you adhere to "GitFlow the Workflow" point for point, why not prevent users from also giving custom names to their branch prefixes like instead of having "feature/yourfeature" you'd have "dogs/yourfeature"? Speaking of which - ironically, I've never had to use anything other than the default branch prefixes. However, not being able to do actions on a dirty working tree? At least weekly, very often multiple times a day.

The reason I'm worked up about it is that there is literally a check in git flow's code for clean working tree before every action. It's like saying, in the familiar shoot-yourself-in-the-foot-metaphor - "here are some nice looking fancy gadgets for your gun that make it easier to shoot, but you can't point it towards the ground with the gadgets attached because that's where your feet are. If you want to point your gun towards the ground, you need to remove the gadgets."

This is why I'd really welcome a (default to false) **configuration option** with "Allow git flow operations with dirty working tree". Can be global, can be repo specific, but would save a lot of time and frustration either way. 

I'm also talking of this for finishing your changes, too, mind you. If an option exists to allow you to shoot towards your foot, there's no reason it should only allow it in some scenarios.

**Comment by petervanderdoes** [comment]
Got it. I'll add a check for a configuration setting as you propose.

**Comment by petervanderdoes** [comment]
Implemented starting commit 310c84a35aa8894ebf9e39f1a846edcf35906272 Development version 1.11.0-dev.23

**Comment by petervanderdoes** [comment]
The config setting to be used is `gitflow.allowdirty`. The wiki will be updated when a new release is send out, hopefully sometime this week, depending on my schedule.
