### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by thedrow** [petervanderdoes/gitflow-avh#202]
There has been some activity after the latest 1.8.0 release.
It's worth releasing a new version.

**Comment by bill-bradley** [comment]
The multi-hotfix option is a feature I'd like in the release.

**Comment by tomschr** [comment]
Just as a reminder: Also document #156 as a reference in the Wiki. :smile:

**Comment by petervanderdoes** [comment]
Darn Wiki I always forget :)

**Comment by silverkorn** [comment]
+1 for a new release soon.

By the way, Git-For-Windows maintainer might prefer this Git-flow version instead of the Nvie's one since it is still maintained.
I would then create a PR to add it in their [MSYS2 packages](https://github.com/git-for-windows/MSYS2-packages) as an updated alternative and potentially as a the main distributed Git-flow.

This said, are Git Flow AVH Edition commands compatible with the original Git Flow from @nvie?

**Comment by silverkorn** [comment]
Nevermind, seems that someone is in charge: https://github.com/git-for-windows/git/issues/416

**Comment by thedrow** [comment]
Is a new version released yet? I don't see a new tag.

**Comment by petervanderdoes** [comment]
https://github.com/petervanderdoes/gitflow-avh/tree/1.9.1

Two tags since 1.8.0, v1.9.0 (which I have to rename) and 1.9.1
