### ISSUE TITLE
Parallel hotfix releases

### ISSUE THREAD

**Issue by rcdailey** [petervanderdoes/gitflow-avh#226]
This is a deviation from gitflow, but we do this at my day job because we need the ability to hotfix any release in the field without introducing features.

This means we release directly on the `hotfix` branch. The SHA1 is tagged on the hotfix branch and we merge the hotfix back to `develop` _only_ (we do not merge it to `master`).

Would it be acceptable to add a feature to your scripts to allow this? I am happy to contribute the change, but I want to make sure this makes sense and that there aren't better alternatives.

**Comment by hungdoan2** [comment]
The same here.
But, I think It's not git-flow issues . It's  work-flow issue.  
You can release directly on the `hotfix`  to make sure our fix is delivered to customer as soon as possible.  But I think I have to merge it to master to make sure my fix is `logged`. Because `hotfix branchs` will be deleted in the future.

**Comment by Wirone** [comment]
Probably I don't understand your flow, but it doesn't look like hotfix in GitFlow context. It's more like support for older, not maintained version.

In this model, hotfix goes from `master` (most recent release) and is merged back. Parallel hotfixes (from and to the same branch) don't make sense because if there are many issues to fix, you fix them at once in one hotfix.

**Comment by rcdailey** [comment]
Each hotfix is based on a different tag. Nothing to do with master.

**Comment by Wirone** [comment]
Of course it's related to `master`. We're in GitFlow repo and its model defines hotfixes as branches that goes from and to `master`. You don't fix tag, you fix application with newer version, starting from current version.

If you do differently, you're not using GitFlow.

**Comment by rcdailey** [comment]
I stated in my original post:

> This is a deviation from gitflow

And per the details there, *this particular issue* has nothing to do with master. This also is a change request, which by definition means not using gitflow, because I'm requesting a change to the rules.

**Comment by rcdailey** [comment]
I'm closing because this issue is years old and decided that gitflow is archaic and not useful for many reasons. I don't use it anymore. Also responses to this issue have gotten rather useless so there's no point in encouraging further discussion.

**Comment by Wirone** [comment]
So you wanted to deviate from Gitflow by requesting breaking change(?) in Gitflow-based repo? Seems legit ;) I totally undestood your request, I just stated it does not make sense in this particular branching model.

**Comment by rcdailey** [comment]
It makes sense in that it is functional, since I've been doing multiple hotfixes (as described) for years now. Gitflow is just too limiting for this specific scenario. I'm less concerned about the scripts following GitFlow, more interested in them being flexible enough to support GitFlow plus some variations. However, I left that judgement up to the actual developers of this repository. Not really interested in the opinions of passersby.

**Comment by hung-doan** [comment]
@rcdailey I agree with you about Gitflow is going to not useful these day. (But It's good practice to begin with) 

Some project, I didn't use the master branch for production because it increase the complexity. Just master for development & tag for productions. 

When it come with CI/CD gitflow become more useless :(

**Comment by Wirone** [comment]
@hung-doan actually Gitflow has NOTHING to do with CI/CD _per se_. It's about releasing/development approach, not about actual deployment. But even in this context, Gitflow IS useful.

We use Docker and with Gitlab CI + Rancher we do:
- automatic deploy `develop` to main DEV instance
- automatic deploy of all feature/hotfix/release branches to specific DEV instances (create them dynamically) so everything can be accessed and checked before merging
- alternatively we use semi-automatic (manual triggering) deploy of feature branches into main DEV instance
- automatic deploy stable versions (on `v*` tags) to Stage instance
- semi-automatic deploy (manual triggering) of stable versions to PROD

`develop` branch MAY BE redundant in some cases, because you could deploy `master` branch to main DEV instance and everything would work the same as described above.

Everything depends on how do you handle releasing - if you do continuous delivery, most probably Gitflow is not for you. But if you work from release to release, you really want `develop` branch because you want to have ability to make hotfix at any moment, without deploying changes made from previous release.

Don't blame the tool / model, just think if it fits your needs. If not, use different model and do not ask for modifying existing one.
