### ISSUE TITLE
git-flow finish cmd always switch HEAD to develop

### ISSUE THREAD

**Issue by zheeeng** [petervanderdoes/gitflow-avh#251]
If you are in feature/f1, `git flow feature finish f1` switch you into develop branch is reasonable, but if you are developing feature/f2, run `git flow feature finish f1`, you would also be popup to develop branch.

**Comment by petervanderdoes** [comment]
Devil's advocate question: Why should a `feature finish` always checkout the develop branch?

**Comment by jrial** [comment]
@petervanderdoes I'd argue it should always checkout the _parent_ branch.

@zheeeng I kind of understand where you come from, but I believe it would replace one problem with another. I'd prefer to know that after every feature finish I end up at exactly the same spot, rather than having to take into consideration what branch I'm on every time I finish a feature, just to figure out where I'll end up.

Both preferences could be appeased by turning it into a configuration setting, but for something like this it seems overkill.
