### ISSUE TITLE
[Question] Ubuntu installation and push origin tags

### ISSUE THREAD

**Issue by cassianotartari** [petervanderdoes/gitflow-avh#277]
Hi!

  I'm starting to play with git flow and when I installed it on Ubuntu with ``sudo apt-get install git-flow`` the installed the version is:
```bash
$ git flow version
1.8.0 (AVH Edition)
```

  When I installed it with: 
```bash
$ wget --no-check-certificate -q  https://raw.github.com/petervanderdoes/gitflow-avh/develop/contrib/gitflow-installer.sh && sudo bash gitflow-installer.sh install stable; rm gitflow-installer.sh
$ git-flow version
1.10.0 (AVH Edition)
```

The problem to use ``git-flow`` instead of  ``git flow`` are the shortcuts in terminal with ``tab`` autocomplete. Using ``git-flow`` doesn't work.

The second question is about push the release tags to remote. I'm playing with a private repository at Github and the release tags are just pushed when I run ``git push origin --tags``. It's not supposed to push to remote with ``git flow release finish 0.2.0`` (for example) ?

Thanks.

**Comment by petervanderdoes** [comment]
The pushing of the tag on a `release finish` is controlled by the flag `--pushtag`

If you always want to push tag on a finish you can set this option by default in the config by running this command: `git config gitflow.release.finish.pushtag yes`. See [git flow configuration](https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-Configuration) and [git flow configuration example](https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-Configuration#example) for more info.

I recommend using `git flow` instead of `git-flow` for the reason you are giving.
