### ISSUE TITLE
Why isn't --no-ff the default for merges?

### ISSUE THREAD

**Issue by pke** [petervanderdoes/gitflow-avh#291]
The original git flow recommended to always use real merges instead of fast-forwards. Why was this recommendation not carried over to this script? I always forget to configure the options (for each branch even!) when setting up a new project/computer.

It would already help if the flag could be configured during `git flow init` as the last step.

**Comment by DerfOh** [comment]
From what I understand the purpose of using --no-ff is used to make a merge commit when merging into a different branch.

**Comment by petervanderdoes** [comment]
The only time a branch should be merged with fast-forward is when the branch only has one commit.

The reason is legacy, sometime in the past there was a discussion and it was determined that if there was only 1 commit on a branch the branch would be merged with `-ff`

If it happens all the time, meaning with to be merged branches that have more than 1 commit please let me know, because something else up then.

**Comment by jkankiewicz** [comment]
Issue #140 should have been referenced here but wasn't so I'm doing so now.
