### ISSUE TITLE
Please add "giflow.feature.finish.push" and "giflow.bugfix.finish.push"

### ISSUE THREAD

**Issue by andreabisiach** [petervanderdoes/gitflow-avh#331]
Hello,

I am pretty new to git flow and I am trying to have a setup for a group of developers that forces them to fetch and push everytime they inititate or finish a bug or feature branch.
for fetch i used config gitflow.feature.start.fetch=true and gitflow.bugfix.start.fetch=true 
I also use gitflow.feature.finish.fetch=true and gitflow.bugfix.finish.fetch=true to ensure they get the latest from development before finishing a bug/feature
I also need "giflow.feature.finish.push" and "giflow.bugfix.finish.push" to ensure that their work is merged back in development and pushed upstream.
Does it make sense?

Regards
Andreas

**Comment by NobbZ** [comment]
Personally I do not think so.

Nothing should be pushed into one of the longlived branches without peer review and CI. Both are able to detect out-of-date branches, and if that happened we still have the opportunity to rebase.

Personally I like to pull a branch, walk into the park and stay disconnected for a couple of hours. After that I present my work to my peer and we merge (or do not). Beeing able to work even offline is one of the greatest things in git.

If your developers aren't disciplined enough to use git proper or forget to push their work at the end of the day, I do not think that you can configure such a problem away. It will just anoy them, and they will change the setting back to false.

**Comment by andreasbisiach** [comment]
I understand your point and maybe my suggestion is based on my "newbie" knowledge of git.
But as arguments form my side:
1) It would be a option as the others (false by default), so it may suit some working scenario but no harm others
2) Why git flow release and git flow hotfix do have a --push option? Your concern should applied to those commands as well

**Comment by NobbZ** [comment]
I'm not sure about the reasoning behind them, but perhaps it is because hotfix and release are usually not done lightheartedly but by a single responsible person against a usually protected branch. But as I said thats only theory.

Also, I do not care for a CLI argument I have to pass explicitely when I want it (`git feature finish stuff --push`). This could save me a lot of typing on the next line, if I were actually still using git flow ;)

It seems as if all of you are pushing to a central repository to the same branch which does conflict a lot because of not synchronised changes, and you seem to want to repair this by forcing your co-workers to synch before doing anything. This might work, but not necessarily have to.

In my company we do infact use a flow similar to the one proposed by the original git flow. But we branch and merge manually. We use a gitlab server internally and use merge requests (similar to github pull requests). No one ever commits directly to develop or master, but creates MRs into those branches. Sometimes his branch will have a merge conflict, but then he rebases and can get merged in easily via web interface.

Of course you can use any other git-hosting service or software as well.

If you do not want to use such services or software, the only other possibility I see, to keep it clean, is still to commit only to ones own branches and push those at the end of the day and having a single person in charge that gets a mail from the developer when a feature is in a mergeable state and then he merges manually. Of course he is the only person allowed to push to develop and master. But I warn you, thats a lot of work to do for a single person...

**Comment by andreasbisiach** [comment]
The primary reason  behind my suggestion is that I want to simplify the git operation for a small goup that is not particolarly skilled in git (less then me and that says it all).
So:
1) gitflow.feature.start.fetch=true (or --fetch) ensures that before starting a feature, they will receive a warning if there are new commits on develop at origin. In this way, the will need to first switch to develop and update it and try again (versus just starting a feature from an older point in time)
2) gitflow.feature.finish.push=true (or --push bot to be implemented) would ensure that when done, develop is updated with the new feature.

Our repositories are hosted at visualstudio.com, they indeed offer pull request services, but given our scenario we try to keep it simple

**Comment by jkankiewicz** [comment]
For me, the justification for item 2 is the last example command invocation within the [Incorporating a finished feature on develop](http://nvie.com/posts/a-successful-git-branching-model/#incorporating-a-finished-feature-on-develop) section of Vincent Driessen's [original document](http://nvie.com/posts/a-successful-git-branching-model/) e.g.
> $ git push origin develop

This is what anyone performing the steps manually would be doing so I was surprised to discover that the `git flow feature finish` command **doesn't** do it by default.
At the very least one should have the option of configuring the command to automate all of the steps that Vincent Driessen specified.

**Comment by jkankiewicz** [comment]
This ticket can be closed; I just discovered to my delight that @petervanderdoes added both the "gitflow.feature.finish.push" and the "gitflow.bugfix.finish.push" configuration settings in version [1.11.0](https://github.com/petervanderdoes/gitflow-avh/tree/1.11.0) (commits [ecce3a07bf087c80d899b2e09526c50ae07b05e2](https://github.com/petervanderdoes/gitflow-avh/commit/ecce3a07bf087c80d899b2e09526c50ae07b05e2#diff-03142f5f0eb720f773e88e1b924acba8) and [3cb09193c2e483dacd9ba2a57382adc2d2414f3f](https://github.com/petervanderdoes/gitflow-avh/commit/3cb09193c2e483dacd9ba2a57382adc2d2414f3f#diff-c798a1c78e422edd426f8f8ce2e14125), respectively).

I've already updated the [Reference: Configuration](https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-Configuration) wiki page to document their existence. :wink:

**Comment by TheDutchCoder** [comment]
What's the reasoning for not enabling this by default?
If you finish a hotfix, git flow will already merge it into develop and master anyway, why wait with pushing?

PR's should be done before finishing anyway.

**Comment by andreabisiach** [comment]
> This ticket can be closed; I just discovered to my delight that @petervanderdoes added both the "gitflow.feature.finish.push" and the "gitflow.bugfix.finish.push" configuration settings in version [1.11.0](https://github.com/petervanderdoes/gitflow-avh/tree/1.11.0) (commits [ecce3a07bf087c80d899b2e09526c50ae07b05e2](https://github.com/petervanderdoes/gitflow-avh/commit/ecce3a07bf087c80d899b2e09526c50ae07b05e2#diff-03142f5f0eb720f773e88e1b924acba8) and [3cb09193c2e483dacd9ba2a57382adc2d2414f3f](https://github.com/petervanderdoes/gitflow-avh/commit/3cb09193c2e483dacd9ba2a57382adc2d2414f3f#diff-c798a1c78e422edd426f8f8ce2e14125), respectively).
> 
> I've already updated the [Reference: Configuration](https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-Configuration) wiki page to document their existence. 😉

Closing since stated as fixed in 1.11.0
