### ISSUE TITLE
flags:ERROR short flag required for (showcommands) on this platform

### ISSUE THREAD

**Issue by mcmire** [petervanderdoes/gitflow-avh#44]
Hey there, starting to use your fork and I am getting this message every time I issue a git flow command:

```
flags:ERROR short flag required for (showcommands) on this platform
```

I believe this may be related to the fact that I am on OS X. I can trace this to shFlags but I'm not sure how to resolve this. Can you give me some insight?

**Comment by eaigner** [comment]
I'm trying to embed `git-flow-avh` into an app, since `git-flow` doesn't work anymore with latest `git` versions. `gnu-getopt` is not really an acceptable solution here.

How do I get around this without patching git flow?

~~~
Git exited with status 2

flags:ERROR short flag required for (showcommands) on this platform
flags:ERROR short flag required for (local) on this platform
flags:ERROR short flag required for (global) on this platform
flags:ERROR short flag required for (system) on this platform
flags:ERROR short flag required for (file) on this platform
flags:WARN getopt: illegal option -- -
getopt: illegal option -- l
getopt: illegal option -- o
getopt: illegal option -- c
getopt: illegal option -- a
getopt: illegal option -- l
 -f -d --
flags:FATAL unable to parse provided options with getopt.
~~~
