### ISSUE TITLE
Sync base branches via pull/push

### ISSUE THREAD

**Issue by kirillsalykin** [petervanderdoes/gitflow-avh#95]
I have published feature branched started not from develop, but from other feature branch.
How it can be synced by other team guys?

AFAIK, all bases stored in gitflow_config - but this file neither pushed/pulled.

Thanks.

**Comment by vladimirfx** [comment]
+1
As now it is kindly  dangerous to share feature/release/bugfix branches started from non default base. Moreover any non default configuration of root branches (develop, features prefix and so on) also not shared by remote. In the age of build tool wrappers, common shared commit hooks, infrastructure descriptors (e.g. Vargrant config ) is very confusing.
Context:
My team is migrated from Mercurial where hgflow is able to manage such non default branches and bases automatically ( .hgflow config file in the repo). After migration to Git we already have several incorrect merges with git-flow because of incorrect base branche. And more are comming, I think... Inter developer communication for that critical things as base branch is IMO very non durable approach. 
As now we use something similar to this aproach:
http://stackoverflow.com/questions/18329621/storing-git-config-as-part-of-the-repository

But we don't need universal config transfer mechanism moreover it is dangerous in many ways.

Implementation suggestions :
1. .gitflow config file should be created on init phase (may be with option) and contains all branch names mapping (develop, master, features prefix and so on). It should be commited in develop and master. 
2. When new feature/release/bugfix/hotfix branch is created .gitflow should be updated with one property - "base" pointing on base branch. 
3. When such non default based branch will be merged by git-frow in any way (not just finished) "base" property should be erased from .gitflow in merge commit. So .gitflow will stay unchanged on root branches (develop, master, support).

As bonus for #1: such mapping config makes possible future change of default mapping without regress on existing repos.
